CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
ALTER EXTENSION pg_stat_statements UPDATE;

CREATE EXTENSION IF NOT EXISTS http;
ALTER EXTENSION http UPDATE;

CREATE EXTENSION IF NOT EXISTS pg_net;
ALTER EXTENSION pg_net UPDATE;

CREATE EXTENSION IF NOT EXISTS pg_cron;
ALTER EXTENSION pg_cron UPDATE;

CREATE EXTENSION IF NOT EXISTS pg_bm25;
ALTER EXTENSION pg_bm25 UPDATE;

CREATE EXTENSION IF NOT EXISTS vector;
ALTER EXTENSION vector UPDATE;

CREATE EXTENSION IF NOT EXISTS age;
ALTER EXTENSION age UPDATE;