model_list:
  - model_name: "*"
    litellm_params:
      model: hosted_vllm/gpt-5
      api_base: https://vllm-example.rebelsoft.com/v1
    model_info:
      input_cost_per_token: 0.000005   # $15.00 per 1M tokens
      output_cost_per_token: 0.000025  # $75.00 per 1M tokens
  - model_name: text-embedding-3-small
    litellm_params:
      model: hosted_vllm/text-embedding-3-small
      api_base: http://embedding.vllm-example:8000/v1
      # drop_params: true
  - model_name: image
    litellm_params:
      model: hosted_vllm/Tongyi-MAI/Z-Image-Turbo
      api_base: https://image-vllm-example.rebelsoft.com/v1
  - model_name: rerank
    litellm_params:
      model: hosted_vllm/rerank
      api_base: https://rerank-vllm-example.rebelsoft.com/v1
  - model_name: qwen3-6-27b-fp8
    litellm_params:
      model: hosted_vllm/Qwen/Qwen3.6-27B-FP8
      api_base: https://txmentsz8rjnstvh.us-east-2.aws.endpoints.huggingface.cloud/v1
      api_key: "${HF_ENDPOINT_KEY}"
      # connect_timeout: 3
      # timeout: 60
      # request_timeout: 60
      # read_timeout: 300
      # stream_timeout: 600
    model_info:
      input_cost_per_token: 0.000005   # $15.00 per 1M tokens
      output_cost_per_token: 0.000025  # $75.00 per 1M tokens
  - model_name: qwen3-6-35b-a3b-fp8
    litellm_params:
      model: hosted_vllm/Qwen/Qwen3.6-35B-A3B-FP8
      api_base: https://irehyld3mmyk6w77.us-east-2.aws.endpoints.huggingface.cloud/v1
      api_key: "${HF_ENDPOINT_KEY}"
      # connect_timeout: 3
      # timeout: 60
      # request_timeout: 60
      # read_timeout: 300
      # stream_timeout: 600
    model_info:
      input_cost_per_token: 0.000005   # $15.00 per 1M tokens
      output_cost_per_token: 0.000025  # $75.00 per 1M tokens
router_settings:
  routing_strategy: simple-shuffle
  # After a failure, wait 5 minutes before trying the primary again
  # This reduces the number of 10-second "hangs" during that 10m recovery
  cooldown_time: 300
  fallbacks: [
    {
      "qwen3-6-27b-fp8": ["*"]
    },
    {
      "qwen3-6-35b-a3b-fp8": ["*"]
    }
  ]

general_settings:
  store_model_in_db: true
  store_prompts_in_spend_logs: true
