connector.name=mysql
connection-url=jdbc:mysql://query-service.databend-example:3307
#connector.name=clickhouse
#connection-url=jdbc:clickhouse://query-service.databend-example:8124
connection-user=databend
connection-password=databend